apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-plugin
spec:
  selector:
    matchLabels:
      app: example-plugin
  template:
    metadata:
      labels:
        app: example-plugin
    spec:
      containers:
      - image: seanshahkarami/example-plugin
        name: example-plugin
        resources:
          limits:
            cpu: 500m
            memory: 20Mi
          requests:
            cpu: 250m
            memory: 10Mi
        volumeMounts:
          - name: uploads
            mountPath: /uploads
      volumes:
      - name: uploads
        hostPath:
          # right... what we can do is generate isolated subdirectories to staging
          # can also be based on plugin id and all that
          # TODO this needs to be built into run
          path: /uploads/example-plugin
          type: DirectoryOrCreate
