apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-plugin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-plugin
  template:
    metadata:
      labels:
        app: example-plugin
    spec:
      containers:
      - image: seanshahkarami/example-plugin
        name: example-plugin
        volumeMounts:
          - name: training-data
            mountPath: /data/training-data
      volumes:
      - name: training-data
        hostPath:
          path: /data/training-data
          type: Directory
