apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rsync-uploader
  labels:
    app.kubernetes.io/name: rsync-uploader
    app.kubernetes.io/version: v0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rsync-uploader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rsync-uploader
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - image: seanshahkarami/rsync-uploader
        name: rsync-uploader
        resources:
          limits:
            cpu: 250m
            memory: 20Mi
          requests:
            cpu: 250m
            memory: 20Mi
        volumeMounts:
        - name: local-data
          mountPath: /data
        - name: remote-data
          mountPath: /remote
      volumes:
      - name: local-data
        hostPath:
          path: /data
          type: DirectoryOrCreate
      - name: remote-data
        hostPath:
          path: /remote
          type: DirectoryOrCreate
