apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rsync-uploader
  labels:
    app.kubernetes.io/name: rsync-uploader
    app.kubernetes.io/version: v0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rsync-uploader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rsync-uploader
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - image: seanshahkarami/rsync-uploader
        name: rsync-uploader
        resources:
          limits:
            cpu: 500m
            memory: 20Mi
          requests:
            cpu: 250m
            memory: 10Mi
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        - name: remote
          mountPath: /remote
        - name: upload-key
          mountPath: "/etc/upload-key"
          readOnly: true
      volumes:
      - name: uploads
        hostPath:
          path: /uploads
          type: DirectoryOrCreate
      - name: remote
        hostPath:
          path: /remote
          type: DirectoryOrCreate
      - name: upload-key
        secret:
          secretName: fake-upload-key
