apiVersion: apps/v1
kind: Deployment
metadata:
  name: "client-example"
spec:
  selector:
    matchLabels:
      app: "client-example"
  template:
    metadata:
      labels:
        app: "client-example"
    spec:
      serviceAccountName: build-robot
      containers:
      - image: "seanshahkarami/client-example"
        name: "client-example"
